"""S14-N3 * two controls that decide whether S14-N1 and S14-N2 mean what they appear to mean.

CONTROL 1 -- is the domain AUC real?  S14-N1 reported domain AUC 1.0000 separating train-period
from test-period inputs, even with all time-like columns removed and with seasons matched, and
the implied importance weights degenerated (median 0.09, every weight below 1, effective sample
size exactly 50%).  Perfect separability in 813 dimensions is the expected artefact, not
evidence: with enough columns a boosted tree can separate almost any two samples.  The control is
to run the identical diagnostic on two windows we KNOW are generated by the same process --
2022-2023 versus 2024 inside the training period.  If that also returns ~1.0, the diagnostic is
measuring "time passed", not harmful covariate shift, and the importance-weighting branch of the
transductive axis is dead on arrival.  A permutation control (shuffled domain labels) fixes the
null.

CONTROL 2 -- what does the replicate floor actually bound?  S14-N2 measured E|y1-y2| = 0.08526 on
scored dev rows for g1 and g2, two designed replicates (VESTAS V126 x6 each, same ridge, same
LDAPS 4x4 box), implying an MAE floor of 0.0568-0.0603 against our achieved 0.13753.  That looks
like enormous headroom, but the two groups share the SAME NWP input, so any error made by the
weather model is COMMON to both and cancels in the difference.  The replicate floor therefore
bounds only the GROUP-SPECIFIC noise and is a lower bound on the true floor, not the floor
itself.  This control decomposes it: E|v1-v2| for measured hub wind, E|pc1-pc2| for the clean
physics power, and E|y1-y2| for metered power, versus the known NWP-to-measured-wind error, so
the common-mode term is stated rather than ignored.
"""
import sys, json
import numpy as np, pandas as pd, lightgbm as lgb
from sklearn.metrics import roc_auc_score
sys.path.insert(0, '/Users/um-yunsang/BARAM2026/research/scratch')
sys.path.insert(0, '/Users/um-yunsang/BARAM2026/research/nodes')
from lib import CAPS

C = ('/Users/um-yunsang/BARAM2026/artifacts/cache/'
     '920be0c458d820e855bf79dd25723146f52ce1736138aedba5e6bc853f1f720b/')
N = '/Users/um-yunsang/BARAM2026/research/nodes/'
S = '/Users/um-yunsang/BARAM2026/research/scratch/'
TIME_LIKE = ('forecast_kst_dtm', 'data_available_kst_dtm', 'forecast_id', 'operating_day',
             'operating_year', 'operating_quarter', 'issuance_batch', 'lead_hour',
             'hour', 'month', 'day_of_year', 'cal__hour_sin', 'cal__hour_cos',
             'cal__doy_sin', 'cal__doy_cos')
CLF = dict(objective='binary', n_estimators=400, learning_rate=0.05, num_leaves=63,
           min_child_samples=60, subsample=0.85, subsample_freq=1, colsample_bytree=0.5,
           reg_lambda=5.0, random_state=20260807, n_jobs=6, verbose=-1)


def auc_of(Xa, Xb, cols, tag):
    X = pd.concat([Xa[cols], Xb[cols]], ignore_index=True).apply(pd.to_numeric, errors='coerce')
    y = np.r_[np.zeros(len(Xa)), np.ones(len(Xb))]
    rng = np.random.default_rng(7); part = rng.integers(0, 3, len(X))
    a = []
    for k in range(3):
        m = lgb.LGBMClassifier(**CLF); m.fit(X[part != k], y[part != k])
        a.append(roc_auc_score(y[part == k], m.predict_proba(X[part == k])[:, 1]))
    print(f'  {tag:46s} n={len(Xa):6d}/{len(Xb):6d}  AUC = {np.mean(a):.4f}')
    return float(np.mean(a))


if __name__ == '__main__':
    tr = pd.read_parquet(C + 'train_features.parquet')
    te = pd.read_parquet(C + 'test_features.parquet')
    num = [c for c in te.columns if c in tr.columns and
           (pd.api.types.is_numeric_dtype(tr[c]) or pd.api.types.is_numeric_dtype(te[c]))]
    notime = [c for c in num if c not in TIME_LIKE]
    out = {}
    print('=== CONTROL 1: is domain AUC 1.0 informative, or an artefact of 813 columns? ===')
    y22 = tr[tr.forecast_kst_dtm < '2024-01-01']
    y24 = tr[tr.forecast_kst_dtm >= '2024-01-01']
    out['train_vs_test'] = auc_of(tr, te, notime, 'train-period vs TEST-period (the claim)')
    out['2022_23_vs_2024'] = auc_of(y22, y24, notime, 'CONTROL 2022-23 vs 2024 (same process!)')
    q2 = tr[(tr.forecast_kst_dtm >= '2023-04-01') & (tr.forecast_kst_dtm < '2023-07-01')]
    q3 = tr[(tr.forecast_kst_dtm >= '2023-07-01') & (tr.forecast_kst_dtm < '2023-10-01')]
    out['Q2_vs_Q3_2023'] = auc_of(q2, q3, notime, 'CONTROL 2023-Q2 vs 2023-Q3 (adjacent quarters)')
    perm = tr.sample(frac=1.0, random_state=1)
    h = len(perm) // 2
    out['random_halves'] = auc_of(perm.iloc[:h], perm.iloc[h:], notime,
                                  'NULL random halves of the training period')
    print('\n  reading: if the 2022-23 vs 2024 control is also near 1.0, the train-vs-test AUC is')
    print('  measuring elapsed time in a 813-column space, not harmful covariate shift, and the')
    print('  importance-weighting branch of the transductive axis is dead.')

    print('\n=== CONTROL 2: what does the replicate floor bound? ===')
    LAB = pd.read_parquet(S + 'labels.parquet').set_index('kst_dtm')
    T = pd.read_parquet(S + 'teacher_targets.parquet')
    cf = pd.DataFrame({g: LAB[f'kpx_group_{g}'] / CAPS[g] for g in (1, 2, 3)})
    dev = (cf.index >= '2023-04-01 01:00') & (cf.index <= '2024-01-01')
    sub = cf[dev].dropna(subset=[1, 2])
    both = sub[(sub[1] >= 0.1) & (sub[2] >= 0.1)]
    v1 = T['g1_v_mean'].reindex(both.index); v2 = T['g2_v_mean'].reindex(both.index)
    p1 = T['g1_pc'].reindex(both.index); p2 = T['g2_pc'].reindex(both.index)
    ok = np.isfinite(v1) & np.isfinite(v2) & np.isfinite(p1) & np.isfinite(p2)
    ev = float(np.abs(v1[ok] - v2[ok]).mean())
    epc = float(np.abs(p1[ok] - p2[ok]).mean())
    ey = float(np.abs(both[1][ok] - both[2][ok]).mean())
    print(f'  E|v1-v2| measured hub wind      = {ev:.4f} m/s   (group-specific, micro-siting)')
    print(f'  NWP -> measured wind RMSE       = 1.49-1.78 m/s  (COMMON to both groups, S3)')
    print(f'  ratio common/group-specific     = {1.6/ev:.2f}x')
    print(f'  E|pc1-pc2| clean physics power  = {epc:.5f}')
    print(f'  E|y1-y2| metered power          = {ey:.5f}')
    print(f'  availability share of replicate gap = {(ey-epc)/ey:.1%}')
    out.update({'E_v1v2': ev, 'E_pc1pc2': epc, 'E_y1y2': ey})
    print('\n  CONCLUSION: the replicate difference cancels the NWP error, which S3 measured at')
    print('  1.49-1.78 m/s versus the 0.93 m/s inter-group spread. The 0.0568-0.0603 replicate')
    print('  floor therefore bounds only the GROUP-SPECIFIC component and is a LOWER bound on the')
    print('  achievable MAE, not the achievable MAE. It does not license the claim that 0.1233 is')
    print('  reachable; it does establish that group-specific noise alone cannot explain our')
    print(f'  0.13753, since the label channel (S13-N1: 0.04804) already matches it.')
    json.dump(out, open(N + 'S14-N3_controls.json', 'w'), indent=1, default=str)
