"""N402 admission: Treeffuser (conditional diffusion over gradient-boosted trees)."""
from __future__ import annotations
import sys, json
from pathlib import Path
sys.path.insert(0, "src")
from baram.loop.registry import SpecRegistry

reg = SpecRegistry(Path("."))
verdict = {
    "spec": "N402",
    "licence_gate": {
        "package": "treeffuser 0.2.0 (PyPI, MIT, first upload 2024-06-11)",
        "note": "an algorithm package, not pretrained weights — the 2026-07-05 weights gate does not apply",
        "result": "PASS",
    },
    "environment_gate": {
        "pins": ["numpy<2.0,>=1.24", "lightgbm==4.3.0", "scikit-learn==1.5.0"],
        "project": ["numpy 2.5.1", "lightgbm 4.7.0", "scikit-learn 1.9.0"],
        "impact": "installing into the project venv downgrades three core libraries, invalidating the "
                  "reproduction of every existing fit and the second-round Private-Score restoration "
                  "requirement. A side venv is possible but adds a documented two-environment contract.",
        "result": "BLOCKED_MITIGABLE",
    },
    "expected_value_gate": {
        "benchmark": "arXiv:2602.13010v2 (Belgian offshore, 9 farms, 4y, day-ahead): "
                     "Treeffuser nCRPS 5.6% vs CQR 5.7% — a 1.8% relative edge",
        "in_project_measurement": "N401 measured CQR (D7_CHRONO_CONFORMAL) at -0.005965 official Total "
                                  "against the accepted D1 under a fold-outside decision layer, "
                                  "failing all four monthly-gate conditions",
        "requirement": 0.023473,
        "reasoning": "Treeffuser starts from CQR's measured -0.005965 deficit and the benchmark grants it "
                     "a 1.8% nCRPS edge. N401 also established that better band calibration did not "
                     "translate into official-metric gain at all. The margin cannot bridge the deficit, "
                     "let alone add the requirement.",
        "result": "FAIL",
    },
    "result": "ADMISSION_FAILED_EXPECTED_VALUE_BELOW_REQUIREMENT",
    "note": "rejected on evidence generated by N401 in this same loop, not on prior belief",
}
s = reg.get("N402")
if s:
    s.status = "retired"
    s.outcome = {"accepted": False, "note": verdict["result"], "detail": verdict}
reg.save()
print(json.dumps(verdict, ensure_ascii=False, indent=1)[:1500])
print("\n남은 score_bearing 후보:", [c.id for c in reg.candidates() if c.score_bearing])
